// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sistema_Controle_Zoologico.Data;

#nullable disable

namespace Sistema_Controle_Zoologico.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250413222502_AdicionarTabelaUsuarios")]
    partial class AdicionarTabelaUsuarios
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Sistema_Controle_Zoologico.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Habitat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PaisOrigem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Animais");
                });

            modelBuilder.Entity("Sistema_Controle_Zoologico.Models.AnimalCuidado", b =>
                {
                    b.Property<int>("AnimalId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CuidadoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AnimalId", "CuidadoId");

                    b.HasIndex("CuidadoId");

                    b.ToTable("AnimalCuidados");
                });

            modelBuilder.Entity("Sistema_Controle_Zoologico.Models.Cuidado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Frequencia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cuidados");
                });

            modelBuilder.Entity("Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Sistema_Controle_Zoologico.Models.AnimalCuidado", b =>
                {
                    b.HasOne("Sistema_Controle_Zoologico.Models.Animal", "Animal")
                        .WithMany("AnimalCuidados")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sistema_Controle_Zoologico.Models.Cuidado", "Cuidado")
                        .WithMany("AnimalCuidados")
                        .HasForeignKey("CuidadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("Cuidado");
                });

            modelBuilder.Entity("Sistema_Controle_Zoologico.Models.Animal", b =>
                {
                    b.Navigation("AnimalCuidados");
                });

            modelBuilder.Entity("Sistema_Controle_Zoologico.Models.Cuidado", b =>
                {
                    b.Navigation("AnimalCuidados");
                });
#pragma warning restore 612, 618
        }
    }
}
